name: OneCycleLR
max_lr: 0.01
total_steps: 120
# 上升多久
pct_start: 0.3
# [cos, linear]
anneal_strategy: cos
# init_lr = max_lr / div_factor
div_factor: 25.0
# min_lr = init_lr / final_div_factor
final_div_factor: 10000.0
